
SELECT 
    EMAIL, 
    MAX(PHONE_NUMBER) as PHONE_NUMBER,
    MAX(FIRST_NAME) as FIRST_NAME,
    MAX(LAST_NAME) as LAST_NAME,
    MAX(ADDRESS_ZIP) as ADDRESS_ZIP,
    MAX(REGISTRATION_DATE) as REGISTRATION_DATE,
    MAX(UPDATED_AT) as UPDATED_DATE,
    CASE 
        WHEN 
            MAX(UPDATED_AT) > DATE_FROM_PARTS(2025,06,30) 
            AND
            MAX(REGISTRATION_DATE) <= DATE_FROM_PARTS(2025,06,30) 
        THEN TRUE 
        ELSE FALSE 
    END AS UPDATED_SINCE_JUL_1 
FROM SILVER_DB.PUBLIC_INSIDER.INT_INSIDER_PROFILE
GROUP BY EMAIL
;